export const INITIAL_STATE = 'INITIAL_STATE';
export const INITIAL_REDUCERS = 'INITIAL_REDUCERS';
export const REDUCER_FACTORY = 'REDUCER_FACTORY';
export const _REDUCER_FACTORY = 'INTERNAL_REDUCER_FACTORY';
